---
# tasks file for openssh (CentOS specific)

- name: Install OpenSSH
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ openssh_packages }}"
  tags:
    - openssh
