---
# tasks file for openssh

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - openssh

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - openssh

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - openssh

- name: Create SFTP system group
  become: yes
  group:
    name: "{{ openssh_server_sftp_group }}"
    system: yes
    state: present
  tags:
    - openssh

- name: Create OpenSSH client configuration
  become: yes
  template:
    src: ssh_config.j2
    dest: "{{ openssh_client_config_file }}"
    owner: "{{ openssh_client_config_file_owner }}"
    group: "{{ openssh_client_config_file_group }}"
    mode: "{{ openssh_client_config_file_mode }}"
  tags:
    - openssh

- name: Create OpenSSH server configuration
  become: yes
  template:
    src: sshd_config.j2
    dest: "{{ openssh_server_config_file }}"
    owner: "{{ openssh_server_config_file_owner }}"
    group: "{{ openssh_server_config_file_group }}"
    mode: "{{ openssh_server_config_file_mode }}"
  notify:
    - restart openssh
  tags:
    - openssh

- name: Start OpenSSH service and enable on boot
  become: yes
  service:
    name: "{{ openssh_service_name }}"
    state: started
    enabled: yes
  tags:
    - openssh
