---
# tasks file for openssh

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: openssh

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: openssh

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: openssh

- name: Create OpenSSH client configuration
  template: >
    src=ssh_config_{{ ansible_distribution }}.j2
    dest=/etc/ssh/ssh_config
    owner=root
    group=root
    mode=0644
  tags: openssh
