---
# tasks file for openssh (Ubuntu specific)

- name: Install OpenSSH
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ openssh_packages }}"
  tags:
    - openssh
